pvdb = {

    'CURRENT'  : {'value': 0.000, 'prec': 3, 'unit': 'mA'},

    'SIPS-BEND-FAM' : {'value': 0.000, 'prec': 3, 'unit': 'A' },
    'SIPS-SFA-FAM'  : {'value': 0.000, 'prec': 3, 'unit': 'A' },
    'SIPS-QFA-FAM'  : {'value': 0.000, 'prec': 3, 'unit': 'A' },
    'SIPS-SDA-FAM'  : {'value': 0.000, 'prec': 3, 'unit': 'A' },
    'SIPS-QDA-FAM'  : {'value': 0.000, 'prec': 3, 'unit': 'A' },
    'SIPS-SD1J-FAM' : {'value': 0.000, 'prec': 3, 'unit': 'A' },
    'SIPS-QF1-FAM'  : {'value': 0.000, 'prec': 3, 'unit': 'A' },
    'SIPS-SF1J-FAM' : {'value': 0.000, 'prec': 3, 'unit': 'A' },
    'SIPS-QF2-FAM'  : {'value': 0.000, 'prec': 3, 'unit': 'A' },
    'SIPS-SD2J-FAM' : {'value': 0.000, 'prec': 3, 'unit': 'A' },
    'SIPS-SD3J-FAM' : {'value': 0.000, 'prec': 3, 'unit': 'A' },
    'SIPS-QF3-FAM'  : {'value': 0.000, 'prec': 3, 'unit': 'A' },
    'SIPS-SF2J-FAM' : {'value': 0.000, 'prec': 3, 'unit': 'A' },
    'SIPS-QF4-FAM'  : {'value': 0.000, 'prec': 3, 'unit': 'A' },
    'SIPS-SF2K-FAM' : {'value': 0.000, 'prec': 3, 'unit': 'A' },
    'SIPS-SD3K-FAM' : {'value': 0.000, 'prec': 3, 'unit': 'A' },
    'SIPS-SD2K-FAM' : {'value': 0.000, 'prec': 3, 'unit': 'A' },
    'SIPS-SF1K-FAM' : {'value': 0.000, 'prec': 3, 'unit': 'A' },
    'SIPS-SD1K-FAM' : {'value': 0.000, 'prec': 3, 'unit': 'A' },
    'SIPS-QDB1-FAM' : {'value': 0.000, 'prec': 3, 'unit': 'A' },
    'SIPS-SDB-FAM'  : {'value': 0.000, 'prec': 3, 'unit': 'A' },
    'SIPS-QFB-FAM'  : {'value': 0.000, 'prec': 3, 'unit': 'A' },
    'SIPS-SFB-FAM'  : {'value': 0.000, 'prec': 3, 'unit': 'A' },
    'SIPS-QDB2-FAM' : {'value': 0.000, 'prec': 3, 'unit': 'A' },

    'SIPA-LIFETIME' : {'value': 0.000, 'prec': 4, 'unit': 'h' },
}
